dev:
  db: 
    host: localhost
    port: 27017
    database: andriybazyuta
    user: admin
    passwd: passwd
  app:
    port: 3002
    url: "http://localhost:3002"
    storage: dir
  vimeo:
    consumerKey: "a3a8e7615f737162c5efb58b4bb26f8c"
    consumerSecret: "50cde6c5783b4f9c"
prod:
  db: 
    host: dbh86.mongolab.com
    port: 27867
    database: andriybazyuta
    user: andriybazyuta
    passwd: andriybazyuta
  app:
    port: 80
    url: "http://andriy.bazyuta.me"
    storage: aws
  vimeo:
    consumerKey: "03b12c924d2906eee7351375a2677c6f"
    consumerSecret: "ab366fd1e7fb6dfd"